In [ ]:
import numpy as np

a= np.array([1,2,3])
print(a)
print("****20 array***")


[1 2 3]
****20 array***


In [ ]:
c=np.array([1,2,3])
print(a)
print("*" * 10)
b=np.array([[5,6,3],[6,1,3]])
print(b)

[1 2 3]
**********
[[5 6 3]
 [6 1 3]]


In [ ]:
c=np.array([[[5,6,3],[6,1,2],[5,2,1]]])
print(c)

[[[5 6 3]
  [6 1 2]
  [5 2 1]]]


In [ ]:
c=np.array([[[5,6,3],[6,1,2],[5,2,1]]])
print(c)
print(a.ndim)
print(b.ndim)
print(c.ndim)

[[[5 6 3]
  [6 1 2]
  [5 2 1]]]
1
2
3


In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(1, 3, 3)


In [ ]:
print(a.size)
print(b.size)
print(c.size)

3
6
9


In [ ]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [ ]:
a=np.arange(11,21)
print(a)
b=np.arange(1,21)
print(b)
print("*****")
b=np.arange(1,21).reshape([4,5,1])
print(b)
d=np.arange(5,51,5).reshape([1,5,2])
print(d)


[11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
*****
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]
  [20]]]
[[[ 5 10]
  [15 20]
  [25 30]
  [35 40]
  [45 50]]]


In [ ]:
a = np.arange(6)
print(a.reshape((2, 3)))

print(a.flatten())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([20,30,40,50,70])

In [ ]:
print("array:",arr)

array: [20 30 40 50 70]


In [ ]:
print("sum:",arr.sum())

sum: 210


In [ ]:
print("mean:",arr.mean())

mean: 42.0


In [ ]:
print("median:",np.median(arr))

median: 40.0


In [ ]:
print("std:",np.std(arr))

std: 17.204650534085253


In [ ]:
print("argmax:",np.argmax(arr))

argmax: 4


In [ ]:
print("argmin:",np.argmin(arr))

argmin: 0


In [ ]:
print("max:",np.max(arr))

max: 70


In [ ]:
print("min:",np.min(arr))

min: 20


In [ ]:
print("variance:",np.var(arr))

variance: 296.0


In [ ]:
xy = np.array([[20,30,40,50,70],[25,35,45,55,77]])
print(xy)

[[20 30 40 50 70]
 [25 35 45 55 77]]


In [ ]:
print("sum:",np.sum(xy, axis=0))

sum: [ 45  65  85 105 147]


In [ ]:
print("mean:",np.mean(xy,axis=0))

mean: [22.5 32.5 42.5 52.5 73.5]


In [ ]:
print("median:",np.median(xy,axis=1))

median: [40. 45.]


In [ ]:
print("cumulative sum:",np.cumsum(arr))

cumulative sum: [ 20  50  90 140 210 235 270 315 370 447]


In [ ]:
print("cumlative product:",np.cumprod(arr))

cumlative product: [               20               600             24000           1200000
          84000000        2100000000       73500000000     3307500000000
   181912500000000 14007262500000000]


In [ ]:
bool_type = np.array([xy,xy,xy])
print("boolean val:",np.any(bool_type))

boolean val: True


In [ ]:
xy = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(xy[-1,1])
print(xy[2,2])

8
9


In [ ]:
arr = np.array([10,20,30,40,50])

print(arr[1:4])
print(arr[:3])
print(arr[2:])
print(arr[::2])

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]


In [ ]:
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(arr2d[0:2,1:3])
print(arr2d[:,0])
print(arr2d[1, :])

[[2 3]
 [5 6]]
[1 4 7]
[4 5 6]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.array([[3,2,1],[5,4,3],[7,6,5]])
s=np.add(a,b)
print(s)

[[ 4  4  4]
 [ 8  8  8]
 [12 12 12]]


In [ ]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.array([[3,2,1],[5,4,3],[7,6,5]])
s=np.subtract(a,b)
print(s)

[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]


In [ ]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.array([[3,2,1],[5,4,3],[7,6,5]])
m=np.multiply(a,b)
print(m)

[[ 3  4  3]
 [15 16 15]
 [35 36 35]]


In [ ]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.array([[3,2,1],[5,4,3],[7,6,5]])
d=np.divide(a,b)
print(d)

[[0.33333333 1.         3.        ]
 [0.6        1.         1.66666667]
 [0.71428571 1.         1.4       ]]


In [ ]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.array([[3,2,1],[5,4,3],[7,6,5]])
c=np.add(a,b)
print(a//b)

[[0 1 3]
 [0 1 1]
 [0 1 1]]


In [ ]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.array([[3,2,1],[5,4,3],[7,6,5]])
c=np.add(a,b)
print(a+4)

[[ 5  6  7]
 [ 7  8  9]
 [ 9 10 11]]


In [ ]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.array([[3,2,1],[5,4,3],[7,6,5]])
c=np.add(a,b)
print(a*3)

[[ 3  6  9]
 [ 9 12 15]
 [15 18 21]]


In [ ]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.array([[3,2,1],[5,4,3],[7,6,5]])
c=np.add(a,b)
print(a**2)

[[ 1  4  9]
 [ 9 16 25]
 [25 36 49]]


In [ ]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.array([[3,2,1],[5,4,3],[7,6,5]])
c=np.add(a,b)
print(a%3)

[[1 2 0]
 [0 1 2]
 [2 0 1]]


In [ ]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.array([[3,2,1],[5,4,3],[7,6,5]])
sqrt=np.sqrt(a)
print(sqrt)

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]
 [2.23606798 2.44948974 2.64575131]]


In [ ]:
a=np.array([[[1,2,3],[3,4,5],[5,6,7]]])
b=np.array([[[3,2,1],[5,4,3],[7,6,5]]])
c=np.array([[[3,4,6],[6,7,8],[8,9,10]]])
sum=np.add(a,b,c)
print(sum)

[[[ 4  4  4]
  [ 8  8  8]
  [12 12 12]]]


In [ ]:
a=np.array([[[1,2,3],[3,4,5],[5,6,7]]])
b=np.array([[[3,2,1],[5,4,3],[7,6,5]]])
c=np.array([[[2,3,5],[5,6,7],[7,4,3]]])
subtract=np.subtract(a,b,c)
print(subtract)

[[[-2  0  2]
  [-2  0  2]
  [-2  0  2]]]


In [ ]:
a=np.array([[[1,2,3],[3,4,5],[5,6,7]]])
b=np.array([[[3,2,1],[5,4,3],[7,6,5]]])
c=np.array([[[2,3,5],[5,6,7],[7,4,3]]])
multiply=np.multiply(a,b,c)
print(multiply)

[[[ 3  4  3]
  [15 16 15]
  [35 36 35]]]


In [ ]:
a=np.array([[[1,2,3],[3,4,5],[5,6,7]]])
b=np.array([[[3,2,1],[5,4,3],[7,6,5]]])
divide=np.divide(a,b)
print(divide)

[[[0.33333333 1.         3.        ]
  [0.6        1.         1.66666667]
  [0.71428571 1.         1.4       ]]]


In [ ]:
a=np.array([[[1,2,3],[3,4,5],[5,6,7]]])
b=np.array([[[3,2,1],[5,4,3],[7,6,5]]])
np.floor_divide=np.floor_divide(a,b)
print(np.floor_divide)

[[[0 1 3]
  [0 1 1]
  [0 1 1]]]


In [ ]:
import numpy as np
a=np.zeros([4,3])
print(a)
a=np.zeros([4,3],dtype=int)
print(a)




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
b=np.ones([3],dtype=int)
print("b",b)
print("dimesion:",b.ndim)

b [1 1 1]
dimesion: 1


In [ ]:
c=np.zeros([3],dtype=int)
print("1-d")
print("c",c)
print("dimension:",c.ndim)

1-d
c [0 0 0]
dimension: 1


In [ ]:
c=np.zeros([1,2,3],dtype=int)
print(c)
d=np.zeros([2,3,4],dtype=int)

[[[0 0 0]
  [0 0 0]]]


In [ ]:
a=np.identity(3,dtype=int)
print(a)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
b=np.eye(4,dtype=int)
print(b)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
print("*"*20)
a=np.full([3,4],4)
print(a)

********************
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [ ]:
b=np.full([4],2)
print(b)
c=np.full([1,2,3],3)
print(c)

[2 2 2 2]
[[[3 3 3]
  [3 3 3]]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[6,7,8],[6,9,10],[6,5,8]])
print(a)
print(b)
c = np.dot(a,b)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 6  7  8]
 [ 6  9 10]
 [ 6  5  8]]
[[ 36  40  52]
 [ 90 103 130]
 [144 166 208]]
